### ISSUE TITLE
Fail to provision aks-engine in eastus or westus2

### ISSUE THREAD

**Issue by shahzzzam** [Azure/aks-engine#4624]
**Describe the bug**

Not sure whats the right channel to report the bug. But I am unable to provision any cluster since last week. Note that I was able to do this before, for whatever reason, the aks-engine cannot standup any pods.

The ARM deployment works fine, I also get a `kubeconfig` at the end. But the `kubectl` is unable to connect to the API server.

I SSH into the master node and found following logs in `kubelet`. There are many such `connection refused` logs.:

```
Aug 20 12:35:38 k8s-master-19010323-0 kubelet[4963]: E0820 12:35:38.458513    4963 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://10.255.255.5:443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 10.255.255.5:443: connect: connection refused
Aug 20 12:35:40 k8s-master-19010323-0 kubelet[4963]: I0820 12:35:40.651527    4963 certificate_manager.go:412] Rotating certificates
Aug 20 12:35:40 k8s-master-19010323-0 kubelet[4963]: E0820 12:35:40.654682    4963 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://10.255.255.5:443/apis/certificates.k8s.io/v1/certificatesigningrequests": dial tcp 10.255.255.5:443: connect: connection refused
Aug 20 12:35:43 k8s-master-19010323-0 kubelet[4963]: I0820 12:35:43.487949    4963 fs.go:127] Filesystem UUIDs: map[806200ec-528c-4d8d-a8d3-5b00071f5c53:/dev/sdb1 C4E4-E7F8:/dev/sdc15 f46d39f9-3841-48db-bbab-86d7a76c3270:/dev/sda1 f89a10d0-2ae6-4411-9086-8ccd221055fd:/dev/sdc1]
```

I guess due to this, it cannot provision other pods because it cannot connect to the api-server.

Note that I have provisioned clusters previously using the same scripts, so was not sure why it's failing today. Can you please help? What could have possibly gone wrong?

**Steps To Reproduce**

**Expected behavior**

**AKS Engine version**
vlabs
**Kubernetes version**
1.19

**Additional context**

```json
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.19",
            "kubernetesConfig": {
                "containerRuntime": "containerd",
                "linuxContainerdURL": "https://mobyartifacts.azureedge.net/moby/moby-containerd/1.4.1+azure/bionic/linux_amd64/moby-containerd_1.4.1+azure-1_amd64.deb",
                "useManagedIdentity": true,
                "userAssignedID": "/subscriptions/69d8cafe-46b3-4147-b870-6aa3679a1762/resourceGroups/teleport-containerd/providers/Microsoft.ManagedIdentity/userAssignedIdentities/userss"
            }
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "",
            "vmSize": "Standard_D2_v3"
        },
        "agentPoolProfiles": [
            {
                "name": "agentpool1",
                "count": 1,
                "vmSize": "Standard_D4s_v3",
                "availabilityProfile": "AvailabilitySet",
                "extensions": []
            }
        ],
        "linuxProfile": {
            "adminUsername": "[[user]]",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "[[publickey]]"
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "[[clientid]]",
            "secret": "[[password]]"
        }
    }
}
```

**Comment by shahzzzam** [comment]
Ping!

**Comment by shahzzzam** [comment]
I need help to understand what might be the cause of this. Can someone help?

**Comment by jackfrancis** [comment]
The api model you provided looks O.K., I'll try to repro.

**Comment by jackfrancis** [comment]
I'm not able to reproduce. A couple things I committed from your pasted api model JSON:

- I didn't use a custom container image (perhaps you are using that intentionally?)
- I didn't include any service principal data (when using user-assigned ID you don't need sp data)

Other than that, building a 1.19 cluster backed by containerd, and using user-assigned ID works as expected.

```
$ k get nodes -o json
NAME                        STATUS   ROLES    AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-agentpool1-29468590-0   Ready    agent    93s     v1.19.13   10.240.0.34    <none>        Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.6+azure
k8s-master-29468590-0       Ready    master   3m50s   v1.19.13   10.255.255.5   <none>        Ubuntu 18.04.5 LTS   5.4.0-1055-azure   containerd://1.4.6+azure
```

**Comment by shahzzzam** [comment]
I retried and used the following api model JSON again

```
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "kubernetesConfig": {
                "containerRuntime": "containerd"
            }
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "",
            "vmSize": "Standard_D2_v3"
        },
        "agentPoolProfiles": [
            {
                "name": "agentpool1",
                "count": 1,
                "vmSize": "Standard_D4s_v3",
                "availabilityProfile": "AvailabilitySet",
                "extensions": []
            }
        ],
        "linuxProfile": {
            "adminUsername": "[[user]]",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": "[[publickey]]"
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "[[clientid]]",
            "secret": "[[password]]"
        }
    }
}
```

It failed with the same issue. Not sure why api-server fails to start, I am still unable to provision any clusters. Can you help me take a look ?
